//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APISoapAlergenos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbRestauranteEntities : DbContext
    {
        public dbRestauranteEntities()
            : base("name=dbRestauranteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbAlerg_Ing> tbAlerg_Ing { get; set; }
        public virtual DbSet<tbAlergenos> tbAlergenos { get; set; }
        public virtual DbSet<tbIng_Plato> tbIng_Plato { get; set; }
        public virtual DbSet<tbIngredientes> tbIngredientes { get; set; }
        public virtual DbSet<tbPlatos> tbPlatos { get; set; }
    }
}
