//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APISoapAlergenos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAlergenos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbAlergenos()
        {
            this.tbAlerg_Ing = new HashSet<tbAlerg_Ing>();
        }
    
        public int id_Alergeno { get; set; }
        public string Nombre_Alergeno { get; set; }
        public string Descripcion_Alergeno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbAlerg_Ing> tbAlerg_Ing { get; set; }
    }
}
