//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APISoapAlergenos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbIng_Plato
    {
        public int id_Ing_Plato { get; set; }
        public int id_Ingrediente { get; set; }
        public int Id_Plato { get; set; }
        public int Cantidad { get; set; }
    
        public virtual tbIngredientes tbIngredientes { get; set; }
        public virtual tbPlatos tbPlatos { get; set; }
    }
}
