//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APISoapAlergenos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPlatos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbPlatos()
        {
            this.tbIng_Plato = new HashSet<tbIng_Plato>();
        }
    
        public int Id_Plato { get; set; }
        public string Nombre_Plato { get; set; }
        public string Descripcion_Plato { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbIng_Plato> tbIng_Plato { get; set; }
    }
}
